version: 1.0.{build}

branches:
  only:
    - master

only_commits:
  message: /build/

image: Ubuntu

build_script:
  - sh: >-
      sh init.sh

      sh build.sh


    artifacts: target/torcd

deploy:
  description: 'torcd major release'
  provider: GitHub
  auth_token:
    secure: 2nykYv14S76Qi9U7J2R3uw7hYqeu6Z/NBNZxO6VdWkpRMujggeQihVMWLc5wH25G
  on:
    branch: master
